### ISSUE TITLE
Proper homepage design for the site.

### ISSUE THREAD

**Issue by oli799** [oli799/code-battles#1]
The design need to be responsive and must include 2 buttons (playing online and playing offline) and the coding_home.svg image.

Place the template file to the resources/views folder.

**Comment by sptutusukanta** [comment]
Hi @oli799, I'm on it :)
Happy to PR for the hacktoberfest season.

**Comment by oli799** [comment]
Hi @sptutusukanta. Okay, if you have any questions, don't be afraid to ask!

**Comment by sptutusukanta** [comment]
Sure.
Thanks for assigning.

**Comment by sptutusukanta** [comment]
Hi @oli799, it looks like the home at this moment is completely the default laravel installation. Can you give some idea on what the home page should include or what is required here?

**Comment by oli799** [comment]
Hi @sptutusukanta , it should be something like [this homepage](https://www.chess.com/play). Must need to include 3 buttons (play online, practise offline, play with a friend) and the coding_home.svg file (located in:  /public/images).
