### ISSUE TITLE
Better Dark Theme for the website

### ISSUE THREAD

**Issue by oli799** [oli799/code-battles#3]
Currently, the dark mode of the website is solved with this line: filter: invert(1) hue-rotate(180deg);

The new dark theme need to include a solution for:
- Predefined dark and Light color palettes
- Typography
- Shadows
- Images

The script for changing and saving theme is located in /resources/js/app.js.
The button for changing theme is located in /resources/views/user/profile.balde.php

Before working on this issue please read [this](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/) and [this](https://css-tricks.com/dark-modes-with-css/) article.

**Comment by raphaelz** [comment]
I can take on this issue.
